export interface In_LoginResponse {
  id: number;
  type: string;
  username: string | null;
  phone: string;
  phone_verified: number;
  email: string | null;
  active: string;
  first_name: string | null;
  last_name: string | null;
  national_code: string | null;
  lat: string | null;
  lon: string | null;
  push_id: string;
  device_id: string;
  lang_id: string;
  api_token: string;
  profile_pic: string | null;
  age: string | null;
  phone2: string | null;
  moved_to: string | null;
  parent_id: string | null;
  created_at: string;
  updated_at: string;
  gender: string;
  birthday: string | null;
  blood_type: string | null;
  base_insurance: string | null;
  supplementary_insurance: string | null;
  address: string | null;
  postal_code: string | null;
  reference_code: string;
  out_of_duty: string;
  lastver: string;
  agreement_id: string;
  invite_code: string | null;
  score: string;
  image: string | null;
  credit: number;
  role_type: any[];
}
