export interface Profile {
  id: number;
  type: number;
  username: string;
  phone: string;
  phone_verified: number;
  email: string | null;
  active: number;
  first_name: string;
  last_name: string | null;
  national_code: string | null;
  lat: number | null;
  lon: number | null;
  push_id: string;
  device_id: string;
  lang_id: number | null;
  api_token: string;
  profile_pic: string;
  age: number | null;
  phone2: string | null;
  moved_to: number;
  parent_id: number | null;
  created_at: string | null;
  updated_at: string;
  gender: string | null;
  birthday: string;
  blood_type: string | null;
  base_insurance: string | null;
  supplementary_insurance: string | null;
  address: string | null;
  postal_code: string | null;
  reference_code: string;
  out_of_duty: number;
  lastver: number;
  agreement_id: number;
  invite_code: string | null;
  score: number;
  image: string | null;
}
