import LoginDialog from "@/layouts/home/loginDialog";

function RandomPage() {
  return (
    <div>
      <div>
        <LoginDialog />
      </div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
      <div>65</div>
    </div>
  );
}

export default RandomPage;
